version: '3.8'

services:
  postgres:
    image: postgres:16.4
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 282
      POSTGRES_DB: shopPetDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shoppet-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopPetDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 282
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
